places = ['france', 'dubai', 'africa', 'italy', 'canada']
print(places)
print('Here is the sorted list')
print(sorted(places))
print('Here is the original list again')
print(places)
places = ['france', 'dubai', 'africa', 'italy', 'canada']
rao = sorted(places, reverse=True)
print("Here is the list in reverse alpahabetical order:") 
print(rao)
print('Here is the original list again')
print(places)
places.reverse()
print("Here is the list in reverse order:") 
print(places)
print('Applying the reverse order() function again, the original list returns')
places.reverse()
print(places)
print("Using the sort() function, here is the list in alphabetical order:") 
places.sort()
print(places)
print("Using the sort(reverse=True) function, here is the list in reverse alphabetical order:") 
places.sort(reverse=True)
print(places)
